import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import {
  ClerkProvider
} from '@clerk/nextjs'
import { Toaster } from "sonner";

export const metadata: Metadata = { 
  title: "Repo Talk AI",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/repotalk.png." }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`} data-color-mode="light">
        <head>
          <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
        </head>
        <body>
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Toaster richColors/>
        </body>
      </html>
    </ClerkProvider>
  );
}
